# Production
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Exclude local node_modules
    environment:
      - NODE_ENV=production
      - AWS_ACCESS_KEY_ID="DO003NB89L7TREA74BHW"
      - AWS_SECRET_ACCESS_KEY="cTm4w/ahaYGQmqv65x7fVsKBY/DWnIOMT7zvuCRwBvE"
    restart: always

  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
      - npm_config_platform=linux
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude local node_modules
    restart: always

    
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"  # Frontend port
#       - "3001:3001"  # Backend port
#     volumes:
#       - .:/app
#     environment:
#       - NODE_ENV=production
#     restart: always



#services:
# backend:
#  build:
#    context: ./backend
#   ports:
#     - "3001:3000"
#   volumes:
#     - ./backend:/app

# frontend:
#   environment:
#     - npm_config_platform=linux
#   build:
#     context: ./frontend
#   ports:
#     - "3000:3000"
#   volumes:
#     - ./frontend:/app

  # test:
  #   build:
  #     context: ./backend
  #   command: npm test
