
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"  # Frontend port
#       - "3001:3001"  # Backend port
#     volumes:
#       - .:/app
#     environment:
#       - NODE_ENV=production
#     restart: always



services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app

  frontend:
    environment:
      - npm_config_platform=linux
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  # test:
  #   build:
  #     context: ./backend
  #   command: npm test
