# Production
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:rw  # Mount certbot conf dir
      - ./certbot/www:/var/www/certbot:rw  # Mount certbot challenge dir
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork
  
  certbot:
    build:
        context: .
        dockerfile: Dockerfile.certbot  # This is your custom Dockerfile for Certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw  # Mount certbot conf dir
      - ./certbot/www:/var/www/certbot:rw  # Mount certbot challenge dir
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure NGINX conf is available to Certbot
    environment:
      - CERTBOT_EMAIL=josh.b.lewis@outlook.com
      - CERTBOT_DOMAIN=finition108.io
    entrypoint: "/bin/sh -c 'certbot certonly --nginx -d finition108.io --config-dir /etc/letsencrypt --work-dir /tmp --logs-dir /tmp'"
    depends_on:
      - nginx
    networks:
      - mynetwork
      
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      retries: 3
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DO_SPACES_KEY=DO003NB89L7TREA74BHW
      - DO_SPACES_SECRET=cTm4w/ahaYGQmqv65x7fVsKBY/DWnIOMT7zvuCRwBvE
      - DO_SPACES_BUCKET=imagery
    restart: always

  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
      - npm_config_platform=linux
      - API_BASE_URL=http://backend:3001
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

networks:
  mynetwork:
    driver: bridge
