# Production
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      - frontend
      - backend
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    
      
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]  # Adjust based on your app's health check
      interval: 30s
      retries: 3
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DO_SPACES_KEY=DO003NB89L7TREA74BHW
      - DO_SPACES_SECRET=cTm4w/ahaYGQmqv65x7fVsKBY/DWnIOMT7zvuCRwBvE
      - DO_SPACES_BUCKET=imagery
    restart: always

  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
      - npm_config_platform=linux
      - API_BASE_URL=http://backend:3001  # Update this to the backend service-name:port in docker
    ports:
      - "3000:3000"  # Expose frontend port
    networks:
      - mynetwork
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

networks:
  mynetwork:
    driver: bridge

    
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"  # Frontend port
#       - "3001:3001"  # Backend port
#     volumes:
#       - .:/app
#     environment:
#       - NODE_ENV=production
#     restart: always



#services:
# backend:
#  build:
#    context: ./backend
#   ports:
#     - "3001:3000"
#   volumes:
#     - ./backend:/app

# frontend:
#   environment:
#     - npm_config_platform=linux
#   build:
#     context: ./frontend
#   ports:
#     - "3000:3000"
#   volumes:
#     - ./frontend:/app

  # test:
  #   build:
  #     context: ./backend
  #   command: npm test
